### PR TITLE
Add ability to select attributes

### PR DESCRIPTION
**Pull request by RichardRobertson**
Created AttrNodeWrapper which disguises IAttr as INode and allows it to be returned from SelectNodes and SelectSingleNode.
Modified HtmlDocumentNavigator to use AttrNodeWrapper when _attrIndex != -1.
Added test case to verify that attributes can be selected.

This fixes issue #23 which was closed but not fixed previously.

This is technically a breaking change if people were relying on the old incorrect behavior of returning the element that owns the attribute instead of the selected attribute itself.

Sorry for the last broken pull request, this one is set up right.

### CODE REVIEW

**Comment by denis-ivanov** [comment]
@RichardRobertson, Thanks for PR.

I asked @FlorianRappl why `IAttr` doesn't inherit `INode`. Let's wait for the answer.

**Comment by FlorianRappl** [comment]
Yeah good point. Actually, `IAttr` should inherit from `INode`, see https://dom.spec.whatwg.org/#interface-attr

**Comment by RichardRobertson** [comment]
I remember reading somewhere that attributes were once nodes, then were changed to not be nodes. I found that weird myself. If AngleSharp will change IAttr to inherit from INode, then the wrapper part of this PR is unnecessary.

At any rate, I look forward to the update that allows attributes to be selected.

**Comment by FlorianRappl** [comment]
> I remember reading somewhere that attributes were once nodes, then were changed to not be nodes.

Yes I guess that may be what happened. Either way, right now WHATWG defines them to be nodes and if I look in Firefox the interface also has all the members of a node. So let's go with it (also solves this issue, which is nice).

The latest AngleSharp preview of 1.0.0 has this change already.

**Comment by RichardRobertson** [comment]
Excellent.

The navigator will still need some small changes to actually return the attribute as the current node (it didn't before this PR) but not having the extra wrapper instance will be much more efficient. I guess we can just close this PR.

Thank you both for your input.

**Comment by FlorianRappl** [comment]
Thanks for bringing this one up @RichardRobertson ! :beers:

**Comment by denis-ivanov** [comment]
> Excellent.
> 
> The navigator will still need some small changes to actually return the attribute as the current node (it didn't before this PR) but not having the extra wrapper instance will be much more efficient. I guess we can just close this PR.
> 
> Thank you both for your input.

I'll try to find free time today and do these changes.

**Pull request closed without merging**
